//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basics.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Basics.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei der Eingabe von {0}. ähnelt.
        /// </summary>
        internal static string EnumValidation_Error {
            get {
                return ResourceManager.GetString("EnumValidation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für {0} muss ein Wert ausgewählt werden. ähnelt.
        /// </summary>
        internal static string EnumValidation_NoSelection {
            get {
                return ResourceManager.GetString("EnumValidation_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei der Eingabe von {0}. ähnelt.
        /// </summary>
        internal static string LinkValidation_Error {
            get {
                return ResourceManager.GetString("LinkValidation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für {0} muss ein Wert ausgewählt werden. ähnelt.
        /// </summary>
        internal static string LinkValidation_NotSpecified {
            get {
                return ResourceManager.GetString("LinkValidation_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei der Eingabe von {0}. ähnelt.
        /// </summary>
        internal static string NumericValidation_Error {
            get {
                return ResourceManager.GetString("NumericValidation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} darf nicht größer als {1} sein. ähnelt.
        /// </summary>
        internal static string NumericValidation_MayNotBiggerThanValue {
            get {
                return ResourceManager.GetString("NumericValidation_MayNotBiggerThanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} darf nicht kleiner als {1} sein. ähnelt.
        /// </summary>
        internal static string NumericValidation_MayNotSmallerThanValue {
            get {
                return ResourceManager.GetString("NumericValidation_MayNotSmallerThanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} muss größer als {1} sein. ähnelt.
        /// </summary>
        internal static string NumericValidation_MustBiggerThanValue {
            get {
                return ResourceManager.GetString("NumericValidation_MustBiggerThanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} muss kleiner als {1} sein. ähnelt.
        /// </summary>
        internal static string NumericValidation_MustSmallerThanValue {
            get {
                return ResourceManager.GetString("NumericValidation_MustSmallerThanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} darf nicht länger als {1} Zeichen lang sein. ähnelt.
        /// </summary>
        internal static string StringValidation_InputTooLong {
            get {
                return ResourceManager.GetString("StringValidation_InputTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} muss mindestens {1} Zeichen lang sein. ähnelt.
        /// </summary>
        internal static string StringValidation_InputTooShort {
            get {
                return ResourceManager.GetString("StringValidation_InputTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} muss eingegeben sein. ähnelt.
        /// </summary>
        internal static string StringValidation_NoInput {
            get {
                return ResourceManager.GetString("StringValidation_NoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} muss genau {1} Zeichen lang sein. ähnelt.
        /// </summary>
        internal static string StringValidation_WrongLength {
            get {
                return ResourceManager.GetString("StringValidation_WrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name muss eindeutig sein. ähnelt.
        /// </summary>
        internal static string UniqueNameValidation_NotUnique {
            get {
                return ResourceManager.GetString("UniqueNameValidation_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} muss eindeutig sein ({1}). ähnelt.
        /// </summary>
        internal static string UniqueValueValidation_NotUnique {
            get {
                return ResourceManager.GetString("UniqueValueValidation_NotUnique", resourceCulture);
            }
        }
    }
}
