//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepotExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DepotExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Addresse ähnelt.
        /// </summary>
        internal static string Addresse {
            get {
                return ResourceManager.GetString("Addresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktie ähnelt.
        /// </summary>
        internal static string Aktie {
            get {
                return ResourceManager.GetString("Aktie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktie wurde verändert. ähnelt.
        /// </summary>
        internal static string AktieHasChanged {
            get {
                return ResourceManager.GetString("AktieHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank ähnelt.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank wurde verändert. ähnelt.
        /// </summary>
        internal static string BankHasChanged {
            get {
                return ResourceManager.GetString("BankHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die Bearbeitung abbrechen? ähnelt.
        /// </summary>
        internal static string CancelEditing {
            get {
                return ResourceManager.GetString("CancelEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} kann nicht gelöscht werden. Es wird von Depots verwendet ({1}). ähnelt.
        /// </summary>
        internal static string CannotDeleteBankUsedByDepots {
            get {
                return ResourceManager.GetString("CannotDeleteBankUsedByDepots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} kann nicht gelöscht werden. Das Wertpapier ist bereits Depots zugeordnet. ähnelt.
        /// </summary>
        internal static string CannotDeleteWertpapierMappedToDepot {
            get {
                return ResourceManager.GetString("CannotDeleteWertpapierMappedToDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktie kann nicht verändert werden, während Depots geöffnet sind. ähnelt.
        /// </summary>
        internal static string CannotEditAktieWhileWorkWithDepot {
            get {
                return ResourceManager.GetString("CannotEditAktieWhileWorkWithDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktie kann nicht verändert werden, während Jahre geöffnet sind. ähnelt.
        /// </summary>
        internal static string CannotEditAktieWhileWorkWithYear {
            get {
                return ResourceManager.GetString("CannotEditAktieWhileWorkWithYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank kann nicht geändert werden, während Depots geöffnet sind. ähnelt.
        /// </summary>
        internal static string CannotEditBankWhileWorkWithDepot {
            get {
                return ResourceManager.GetString("CannotEditBankWhileWorkWithDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fond kann nicht geändert werden, während Depots geöffnet sin. ähnelt.
        /// </summary>
        internal static string CannotEditFondWhileWorkWithDepot {
            get {
                return ResourceManager.GetString("CannotEditFondWhileWorkWithDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fond kann nicht geändert werden, während Jahre geöffnet sind. ähnelt.
        /// </summary>
        internal static string CannotEditFondWhileWorkWithYear {
            get {
                return ResourceManager.GetString("CannotEditFondWhileWorkWithYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei {0} nicht gefunden. ähnelt.
        /// </summary>
        internal static string CannotFindUserSettings {
            get {
                return ResourceManager.GetString("CannotFindUserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stammdaten können nicht gelesen werden. ähnelt.
        /// </summary>
        internal static string CannotLoadMasterdata {
            get {
                return ResourceManager.GetString("CannotLoadMasterdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktie kann nicht gelöscht werden, während Depots geöffnet sind. ähnelt.
        /// </summary>
        internal static string CannotRemoveAktieWhileWorkWithDepot {
            get {
                return ResourceManager.GetString("CannotRemoveAktieWhileWorkWithDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktie kann nicht gelöscht werden, während Jahre geöffnet sind. ähnelt.
        /// </summary>
        internal static string CannotRemoveAktieWhileWorkWithYear {
            get {
                return ResourceManager.GetString("CannotRemoveAktieWhileWorkWithYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank kann nicht gelöscht werden, während Depots geöffnet sind. ähnelt.
        /// </summary>
        internal static string CannotRemoveBankWhileWorkWithDepot {
            get {
                return ResourceManager.GetString("CannotRemoveBankWhileWorkWithDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fond kann nicht gelöscht werden, während Depots geöffnet sind. ähnelt.
        /// </summary>
        internal static string CannotRemoveFondWhileWorkWithDepot {
            get {
                return ResourceManager.GetString("CannotRemoveFondWhileWorkWithDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fond kann nicht gelöscht werden, während Jahre geöffnet sind. ähnelt.
        /// </summary>
        internal static string CannotRemoveFondWhileWorkWithYear {
            get {
                return ResourceManager.GetString("CannotRemoveFondWhileWorkWithYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depot kann nicht geöffnet werden, während Aktien verändert werden. ähnelt.
        /// </summary>
        internal static string CannotWorkWithDepotWhileEditingAktie {
            get {
                return ResourceManager.GetString("CannotWorkWithDepotWhileEditingAktie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depot kann nicht geöffnet werden, während Banken verändert werden. ähnelt.
        /// </summary>
        internal static string CannotWorkWithDepotWhileEditingBank {
            get {
                return ResourceManager.GetString("CannotWorkWithDepotWhileEditingBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depot kann nicht geöffnet werden, während Fonds verändert werden. ähnelt.
        /// </summary>
        internal static string CannotWorkWithDepotWhileEditingFond {
            get {
                return ResourceManager.GetString("CannotWorkWithDepotWhileEditingFond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jahr kann nicht geöffnet werden, während Aktien geändert werden. ähnelt.
        /// </summary>
        internal static string CannotWorkWithYearWhileEditingAktie {
            get {
                return ResourceManager.GetString("CannotWorkWithYearWhileEditingAktie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jahr kann nicht geöffnet werden, während Fonds geändert werden. ähnelt.
        /// </summary>
        internal static string CannotWorkWithYearWhileEditingFond {
            get {
                return ResourceManager.GetString("CannotWorkWithYearWhileEditingFond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten ({0}) werden geändert. ähnelt.
        /// </summary>
        internal static string DataAreChanged {
            get {
                return ResourceManager.GetString("DataAreChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Öffnen der Datenbank: {0}. ähnelt.
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die {0} wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteAktie {
            get {
                return ResourceManager.GetString("DeleteAktie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie die {0} wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteBank {
            get {
                return ResourceManager.GetString("DeleteBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie das {0} wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteDepot {
            get {
                return ResourceManager.GetString("DeleteDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie den {0} wirklich löschen? ähnelt.
        /// </summary>
        internal static string DeleteFonds {
            get {
                return ResourceManager.GetString("DeleteFonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depot ähnelt.
        /// </summary>
        internal static string Depot {
            get {
                return ResourceManager.GetString("Depot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depot wurde verändert. ähnelt.
        /// </summary>
        internal static string DepotHasChanged {
            get {
                return ResourceManager.GetString("DepotHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fond ähnelt.
        /// </summary>
        internal static string Fond {
            get {
                return ResourceManager.GetString("Fond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wertpapier wurde verändert. ähnelt.
        /// </summary>
        internal static string FondHasChanged {
            get {
                return ResourceManager.GetString("FondHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anteile ähnelt.
        /// </summary>
        internal static string HeaderBestandControlAnteile {
            get {
                return ResourceManager.GetString("HeaderBestandControlAnteile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dividende ähnelt.
        /// </summary>
        internal static string HeaderBestandControlDividende {
            get {
                return ResourceManager.GetString("HeaderBestandControlDividende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kauf ähnelt.
        /// </summary>
        internal static string HeaderBestandControlKauf {
            get {
                return ResourceManager.GetString("HeaderBestandControlKauf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verkauf ähnelt.
        /// </summary>
        internal static string HeaderBestandControlVerkauf {
            get {
                return ResourceManager.GetString("HeaderBestandControlVerkauf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wertpapier ähnelt.
        /// </summary>
        internal static string HeaderBestandControlWertpapier {
            get {
                return ResourceManager.GetString("HeaderBestandControlWertpapier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jahr ähnelt.
        /// </summary>
        internal static string HeaderKursControlJahr {
            get {
                return ResourceManager.GetString("HeaderKursControlJahr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wert ähnelt.
        /// </summary>
        internal static string HeaderKursControlWert {
            get {
                return ResourceManager.GetString("HeaderKursControlWert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wertpapier ähnelt.
        /// </summary>
        internal static string HeaderKursControlWertpapier {
            get {
                return ResourceManager.GetString("HeaderKursControlWertpapier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für jedes Jahr darf nur ein Kurs erfasst werden ({0}). ähnelt.
        /// </summary>
        internal static string JahresKursDoppelt {
            get {
                return ResourceManager.GetString("JahresKursDoppelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Kurse sind nicht lückenlos ähnelt.
        /// </summary>
        internal static string JahresKurseNichtLueckenlos {
            get {
                return ResourceManager.GetString("JahresKurseNichtLueckenlos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kurse wurden geändert. ähnelt.
        /// </summary>
        internal static string KurseWereChanged {
            get {
                return ResourceManager.GetString("KurseWereChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Depotentwicklungsdaten ähnelt.
        /// </summary>
        internal static string LoadDepotEntwicklungData {
            get {
                return ResourceManager.GetString("LoadDepotEntwicklungData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Fondentwicklungsdaten ähnelt.
        /// </summary>
        internal static string LoadFondEntwicklungData {
            get {
                return ResourceManager.GetString("LoadFondEntwicklungData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Fonds für Depot ähnelt.
        /// </summary>
        internal static string LoadFondsForDepot {
            get {
                return ResourceManager.GetString("LoadFondsForDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade die Jahresabschlussdaten ähnelt.
        /// </summary>
        internal static string LoadJahresAbschlussData {
            get {
                return ResourceManager.GetString("LoadJahresAbschlussData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie das Programm beenden? ähnelt.
        /// </summary>
        internal static string TerminateProgramm {
            get {
                return ResourceManager.GetString("TerminateProgramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depot Explorer ähnelt.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auswahl der Fonds für {0} ähnelt.
        /// </summary>
        internal static string TitleZuordnungsDialog {
            get {
                return ResourceManager.GetString("TitleZuordnungsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für jedes Jahr dürfen die Bestände für ein Wertpapier nur einmal erfasst werden ({0}). ähnelt.
        /// </summary>
        internal static string WertpapierBestandDoppelt {
            get {
                return ResourceManager.GetString("WertpapierBestandDoppelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für jedes Wertpapier darf nur ein Kurs erfasst werden ({0}). ähnelt.
        /// </summary>
        internal static string WertpapierKursDoppelt {
            get {
                return ResourceManager.GetString("WertpapierKursDoppelt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die WKN existiert bereits. ähnelt.
        /// </summary>
        internal static string WKNValidationNotUnique {
            get {
                return ResourceManager.GetString("WKNValidationNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jahr ähnelt.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuordnungen wurden verändert. ähnelt.
        /// </summary>
        internal static string ZuordnungenWereChanged {
            get {
                return ResourceManager.GetString("ZuordnungenWereChanged", resourceCulture);
            }
        }
    }
}
