//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VermoegensData.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VermoegensData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktie ähnelt.
        /// </summary>
        internal static string Aktie {
            get {
                return ResourceManager.GetString("Aktie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktien ähnelt.
        /// </summary>
        internal static string Aktien {
            get {
                return ResourceManager.GetString("Aktien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutschland ähnelt.
        /// </summary>
        internal static string AktuellesLand {
            get {
                return ResourceManager.GetString("AktuellesLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anbieter ähnelt.
        /// </summary>
        internal static string Anbieter {
            get {
                return ResourceManager.GetString("Anbieter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bank ähnelt.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Banken ähnelt.
        /// </summary>
        internal static string Banken {
            get {
                return ResourceManager.GetString("Banken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Bankleitzahl existiert bereits ähnelt.
        /// </summary>
        internal static string BlzValidation_NotUnique {
            get {
                return ResourceManager.GetString("BlzValidation_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Bankleitzahl hat ein falsches Format. ähnelt.
        /// </summary>
        internal static string BlzValidation_WrongFormat {
            get {
                return ResourceManager.GetString("BlzValidation_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbankversion ähnelt.
        /// </summary>
        internal static string DBVersion {
            get {
                return ResourceManager.GetString("DBVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank-Version kann nicht gelesen werden ähnelt.
        /// </summary>
        internal static string DBVersionCheckingSyntax_Error {
            get {
                return ResourceManager.GetString("DBVersionCheckingSyntax_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Falsche Datenbank-Version: Erwarte {0}.{1}, Datenbank hat {2}.{3} ähnelt.
        /// </summary>
        internal static string DBVersionCheckingVersion_Error {
            get {
                return ResourceManager.GetString("DBVersionCheckingVersion_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabelle mit der Datenbank-Version nicht gefunden ähnelt.
        /// </summary>
        internal static string DBVersionLoading_Error {
            get {
                return ResourceManager.GetString("DBVersionLoading_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depot ähnelt.
        /// </summary>
        internal static string Depot {
            get {
                return ResourceManager.GetString("Depot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Depots ähnelt.
        /// </summary>
        internal static string Depots {
            get {
                return ResourceManager.GetString("Depots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fond ähnelt.
        /// </summary>
        internal static string Fond {
            get {
                return ResourceManager.GetString("Fond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fonds ähnelt.
        /// </summary>
        internal static string Fonds {
            get {
                return ResourceManager.GetString("Fonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ISIN existiert bereits. ähnelt.
        /// </summary>
        internal static string ISINValidation_NotUnique {
            get {
                return ResourceManager.GetString("ISINValidation_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die ISIN hat ein falsches Format. ähnelt.
        /// </summary>
        internal static string ISINValidation_WrongFormat {
            get {
                return ResourceManager.GetString("ISINValidation_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jahr ähnelt.
        /// </summary>
        internal static string Jahr {
            get {
                return ResourceManager.GetString("Jahr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jahre ähnelt.
        /// </summary>
        internal static string Jahre {
            get {
                return ResourceManager.GetString("Jahre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Wertpapiere fürs Depot ähnelt.
        /// </summary>
        internal static string LadeWertpapiereForDepot {
            get {
                return ResourceManager.GetString("LadeWertpapiereForDepot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Länder ähnelt.
        /// </summary>
        internal static string Laender {
            get {
                return ResourceManager.GetString("Laender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Land hat ein falsches Format. ähnelt.
        /// </summary>
        internal static string LandValidation_WrongFormat {
            get {
                return ResourceManager.GetString("LandValidation_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Daten für das Depot ähnelt.
        /// </summary>
        internal static string LoadDepotEntwicklungData {
            get {
                return ResourceManager.GetString("LoadDepotEntwicklungData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade den Jahresabschluss für das Depot ähnelt.
        /// </summary>
        internal static string LoadDepotJahresAbschlussData {
            get {
                return ResourceManager.GetString("LoadDepotJahresAbschlussData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Daten des Wertpapiers vom Depot ähnelt.
        /// </summary>
        internal static string LoadDepotWertpapierEntwicklungData {
            get {
                return ResourceManager.GetString("LoadDepotWertpapierEntwicklungData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Lesen der {0} ähnelt.
        /// </summary>
        internal static string LoadingObjectsError {
            get {
                return ResourceManager.GetString("LoadingObjectsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine {0} gefunden ähnelt.
        /// </summary>
        internal static string LoadingObjectsNoData {
            get {
                return ResourceManager.GetString("LoadingObjectsNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade Daten für die Jahresübersicht ähnelt.
        /// </summary>
        internal static string LoadJahresUebersichtData {
            get {
                return ResourceManager.GetString("LoadJahresUebersichtData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Objekt-Typen ähnelt.
        /// </summary>
        internal static string ObjektTypen {
            get {
                return ResourceManager.GetString("ObjektTypen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Prüfen der Objekt-Typen ähnelt.
        /// </summary>
        internal static string ObjektTypenChecking_Error {
            get {
                return ResourceManager.GetString("ObjektTypenChecking_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Laden der Objekt-Typen ähnelt.
        /// </summary>
        internal static string ObjektTypenLoading_Error {
            get {
                return ResourceManager.GetString("ObjektTypenLoading_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Ort hat ein falsches Format. ähnelt.
        /// </summary>
        internal static string OrtValidation_WrongFormat {
            get {
                return ResourceManager.GetString("OrtValidation_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Postleitzahl hat ein falsches Format. ähnelt.
        /// </summary>
        internal static string PLZValidation_WrongFormat {
            get {
                return ResourceManager.GetString("PLZValidation_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Regionen ähnelt.
        /// </summary>
        internal static string Regionen {
            get {
                return ResourceManager.GetString("Regionen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Themen ähnelt.
        /// </summary>
        internal static string Themen {
            get {
                return ResourceManager.GetString("Themen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wertpapiere ähnelt.
        /// </summary>
        internal static string Wertpapiere {
            get {
                return ResourceManager.GetString("Wertpapiere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die WKN existiert bereits. ähnelt.
        /// </summary>
        internal static string WKNValidation_NotUnique {
            get {
                return ResourceManager.GetString("WKNValidation_NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die WKN hat ein falsches Format. ähnelt.
        /// </summary>
        internal static string WKNValidation_WrongFormat {
            get {
                return ResourceManager.GetString("WKNValidation_WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuordnungen ähnelt.
        /// </summary>
        internal static string Zuordnungen {
            get {
                return ResourceManager.GetString("Zuordnungen", resourceCulture);
            }
        }
    }
}
